import { ClientOnly, createFileRoute } from "@tanstack/react-router";
import { queryOptions, useQueryClient, useSuspenseQuery } from "@tanstack/react-query";
import { useServerFn } from "@tanstack/react-start";
import { Activity, AlertTriangle, Ban, Bell, CircleDollarSign, Download, FileSpreadsheet, Fingerprint, Gauge, Globe2, Radio, ScanLine, Search, ShieldCheck, ShieldX, Sparkles, UploadCloud } from "lucide-react";
import { useEffect, useMemo, useRef, useState, type DragEvent, type ReactNode } from "react";
import { Area, AreaChart, CartesianGrid, ResponsiveContainer, Tooltip, XAxis, YAxis } from "recharts";

import { ParticleField } from "@/components/fraud/particle-field";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Dialog, DialogContent, DialogDescription, DialogFooter, DialogHeader, DialogTitle } from "@/components/ui/dialog";
import { Input } from "@/components/ui/input";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
import { Slider } from "@/components/ui/slider";
import { Tabs, TabsContent, TabsList, TabsTrigger } from "@/components/ui/tabs";
import { Table, TableBody, TableCell, TableHead, TableHeader, TableRow } from "@/components/ui/table";
import { supabase } from "@/integrations/supabase/client";
import { calculateClassificationMetrics, scoreFraudVector, type FraudStatus, type FraudVector } from "@/lib/fraud-model";
import { analyzeTransaction, listTransactions, scoreTransactionBatch } from "@/lib/transactions.functions";
import { cn } from "@/lib/utils";

const transactionsQuery = queryOptions({ queryKey: ["monitored-transactions"], queryFn: () => listTransactions(), staleTime: 15_000 });

export const Route = createFileRoute("/")({
  loader: ({ context }) => context.queryClient.ensureQueryData(transactionsQuery),
  head: () => ({ meta: [
    { title: "FinShield Enterprise | Fraud Control Center" },
    { name: "description", content: "Monitor live card transactions, validate PCA signals, score CSV batches, and stop high-risk payments in real time." },
    { property: "og:title", content: "FinShield Enterprise Fraud Control Center" },
    { property: "og:description", content: "Real-time credit card anomaly tracking and PCA feature validation for fraud teams." },
    { property: "og:type", content: "website" },
    { name: "twitter:card", content: "summary_large_image" },
  ] }),
  component: FraudCommandCenter,
});

type Transaction = Awaited<ReturnType<typeof listTransactions>>[number];
type SandboxValues = FraudVector;
type BatchResult = Awaited<ReturnType<typeof scoreTransactionBatch>>[number];
const initialVector: SandboxValues = { amount: 1850, time: 42800, v14: -1.2, v4: 1.7, v12: -0.8, v10: -0.5 };
const vectorFields = [
  ["amount", "Amount", 0, 10000, 50, "$"], ["time", "Time", 0, 172800, 100, "s"], ["v14", "V14", -10, 5, 0.1, ""],
  ["v4", "V4", -5, 10, 0.1, ""], ["v12", "V12", -10, 5, 0.1, ""], ["v10", "V10", -10, 5, 0.1, ""],
] as const;

const money = (value: number | string) => new Intl.NumberFormat("en-US", { style: "currency", currency: "USD", maximumFractionDigits: 0 }).format(Number(value));
const timeLabel = (value: string) => new Intl.DateTimeFormat("en-US", { hour: "2-digit", minute: "2-digit", second: "2-digit", hour12: false }).format(new Date(value));
const riskTone = (score: number) => score >= 80 ? "text-destructive" : score >= 50 ? "text-amber-400" : "text-emerald-400";
const statusStyle = (status: string) => status === "Blocked" ? "border-destructive/35 bg-destructive/10 text-destructive" : status === "Flagged" ? "border-amber-400/35 bg-amber-400/10 text-amber-400" : "border-emerald-400/25 bg-emerald-400/10 text-emerald-400";

function FraudCommandCenter() {
  const { data: transactions } = useSuspenseQuery(transactionsQuery);
  const queryClient = useQueryClient();
  const [activeTab, setActiveTab] = useState("overview");
  const [threshold, setThreshold] = useState(0.5);
  useEffect(() => {
    const channel = supabase.channel("finshield-transactions-feed").on("postgres_changes", { event: "*", schema: "public", table: "monitored_transactions" }, () => { void queryClient.invalidateQueries({ queryKey: transactionsQuery.queryKey }); }).subscribe();
    return () => { void supabase.removeChannel(channel); };
  }, [queryClient]);
  const blocked = transactions.filter((row) => row.status === "Blocked").length;
  const flagged = transactions.filter((row) => row.status === "Flagged").length;
  const volume = transactions.reduce((total, row) => total + Number(row.amount), 0);
  const threat = transactions.length ? Math.round(transactions.reduce((sum, row) => sum + Number(row.risk_score), 0) / transactions.length) : 0;
  const metrics = calculateClassificationMetrics(transactions.map((row) => ({ riskScore: Number(row.risk_score), status: row.status })), threshold);

  return <main className="relative min-h-screen overflow-hidden bg-background text-foreground">
    <ParticleField />
    <div className="pointer-events-none fixed inset-0 -z-10 bg-[radial-gradient(circle_at_50%_-20%,color-mix(in_oklab,var(--primary)_10%,transparent),transparent_45%),linear-gradient(to_bottom,color-mix(in_oklab,var(--background)_72%,transparent),var(--background))]" />
    <div className="mx-auto max-w-[1540px] px-4 py-5 sm:px-6 lg:px-8">
      <Header />
      <Tabs value={activeTab} onValueChange={setActiveTab} className="mt-5">
        <TabsList className="grid h-auto w-full grid-cols-3 border border-border/70 bg-card/60 p-1 backdrop-blur-xl lg:w-[760px]">
          <TabsTrigger value="overview" className="gap-2 py-2.5 font-mono text-[9px] uppercase sm:text-xs"><Activity /> Overview Hub</TabsTrigger>
          <TabsTrigger value="stream" className="gap-2 py-2.5 font-mono text-[9px] uppercase sm:text-xs"><Radio /> Anomaly Map</TabsTrigger>
          <TabsTrigger value="sandbox" className="gap-2 py-2.5 font-mono text-[9px] uppercase sm:text-xs"><ScanLine /> Risk Sandbox</TabsTrigger>
        </TabsList>
        <TabsContent value="overview" className="mt-5 animate-fade-in"><Overview transactions={transactions} volume={volume} blocked={blocked} flagged={flagged} threat={threat} threshold={threshold} setThreshold={setThreshold} metrics={metrics} /></TabsContent>
        <TabsContent value="stream" className="mt-5 animate-fade-in"><TransactionStream transactions={transactions} /></TabsContent>
        <TabsContent value="sandbox" className="mt-5 animate-fade-in"><RiskSandbox threshold={threshold} /></TabsContent>
      </Tabs>
    </div>
  </main>;
}

function Header() {
  return <header className="glass-panel relative flex min-h-20 items-center justify-between overflow-hidden rounded-md px-4 py-4 sm:px-6">
    <div className="absolute bottom-0 left-0 h-px w-1/3 gold-rule animate-scanline" />
    <div className="flex items-center gap-3"><div className="grid size-10 place-items-center border border-primary/35 bg-primary/10 text-primary"><Fingerprint className="size-5" /></div><div><div className="flex flex-wrap items-center gap-2"><h1 className="text-lg font-semibold sm:text-xl">FINSHIELD ENTERPRISE</h1><Badge variant="outline" className="border-primary/25 font-mono text-[9px] text-primary">GBM · PCA CORE</Badge></div><p className="font-mono text-[10px] uppercase text-muted-foreground">Fraud control center / live anomaly defense</p></div></div>
    <div className="hidden items-center gap-5 md:flex"><div className="text-right"><p className="font-mono text-[10px] uppercase text-muted-foreground">System integrity</p><p className="mt-1 flex items-center gap-2 text-xs text-emerald-400"><span className="size-1.5 animate-pulse rounded-full bg-emerald-400" /> All nodes operational</p></div><Button variant="terminal" size="icon" aria-label="Security alerts"><Bell /></Button></div>
  </header>;
}

function Overview({ transactions, volume, blocked, flagged, threat, threshold, setThreshold, metrics }: { transactions: Transaction[]; volume: number; blocked: number; flagged: number; threat: number; threshold: number; setThreshold: (value: number) => void; metrics: ReturnType<typeof calculateClassificationMetrics> }) {
  const chartData = useMemo(() => [...transactions].reverse().map((row) => ({ time: timeLabel(row.timestamp), volume: Number(row.amount), risk: Number(row.risk_score) * 100 })), [transactions]);
  return <div className="space-y-5">
    <section className="grid gap-4 md:grid-cols-3">
      <Metric icon={<CircleDollarSign />} label="Total monitored card volume" value={money(volume)} detail={`${transactions.length} vectors analyzed`} />
      <div className="glass-panel relative min-h-44 overflow-hidden rounded-md p-5"><div className="flex items-start justify-between"><div><p className="font-mono text-[10px] uppercase text-muted-foreground">Operational threat level</p><p className={cn("mt-2 text-2xl font-semibold", threat >= 60 ? "text-destructive" : "text-primary")}>{threat >= 60 ? "ELEVATED" : "GUARDED"}</p></div><Gauge className="size-5 text-primary" /></div><div className="mt-3 flex items-end justify-between"><svg viewBox="0 0 100 55" className="h-20 w-40" aria-label={`Threat level ${threat} percent`}><path d="M10 50 A40 40 0 0 1 90 50" fill="none" stroke="var(--muted)" strokeWidth="8" strokeLinecap="round" /><path d="M10 50 A40 40 0 0 1 90 50" fill="none" stroke="var(--primary)" strokeWidth="8" strokeLinecap="round" pathLength="100" strokeDasharray={`${threat} 100`} className="animate-gauge" /></svg><div className="pb-2 text-right"><p className="font-mono text-3xl text-primary">{threat}</p><p className="font-mono text-[9px] text-muted-foreground">RISK INDEX</p></div></div></div>
      <Metric icon={<Ban />} label="Blocked anomaly cases" value={String(blocked)} detail={`${flagged} under review`} danger />
    </section>
    <section className="grid gap-5 xl:grid-cols-[minmax(0,1.55fr)_minmax(340px,.7fr)]">
      <div className="glass-panel rounded-md p-4 sm:p-6"><div className="mb-5 flex items-center justify-between"><div><p className="font-mono text-[10px] uppercase text-primary">Network throughput</p><h2 className="mt-1 text-lg font-semibold">Traffic volume & fraud spikes</h2></div><Badge variant="outline" className="border-emerald-400/25 text-emerald-400"><Radio className="mr-1 size-3 animate-pulse" /> Live</Badge></div><ClientOnly fallback={<div className="h-72 animate-pulse bg-muted/30" />}><div className="h-72 w-full"><ResponsiveContainer width="100%" height="100%"><AreaChart data={chartData} margin={{ top: 12, right: 10, left: -12, bottom: 0 }}><defs><linearGradient id="goldArea" x1="0" y1="0" x2="0" y2="1"><stop offset="0%" stopColor="var(--primary)" stopOpacity={0.42} /><stop offset="100%" stopColor="var(--primary)" stopOpacity={0} /></linearGradient><linearGradient id="riskArea" x1="0" y1="0" x2="0" y2="1"><stop offset="0%" stopColor="var(--destructive)" stopOpacity={0.34} /><stop offset="100%" stopColor="var(--destructive)" stopOpacity={0} /></linearGradient></defs><CartesianGrid vertical={false} stroke="var(--border)" strokeDasharray="3 6" /><XAxis dataKey="time" stroke="var(--muted-foreground)" fontSize={10} tickLine={false} axisLine={false} /><YAxis stroke="var(--muted-foreground)" fontSize={10} tickLine={false} axisLine={false} tickFormatter={(value) => `$${Math.round(value / 1000)}k`} /><Tooltip contentStyle={{ background: "var(--popover)", border: "1px solid var(--border)", borderRadius: "4px" }} /><Area type="monotone" dataKey="volume" name="Volume ($)" stroke="var(--primary)" strokeWidth={2} fill="url(#goldArea)" isAnimationActive={false} /><Area type="monotone" dataKey="risk" name="Risk signal" stroke="var(--destructive)" strokeWidth={2} fill="url(#riskArea)" isAnimationActive={false} /></AreaChart></ResponsiveContainer></div></ClientOnly></div>
      <div className="glass-panel rounded-md p-5"><p className="font-mono text-[10px] uppercase text-primary">Decision intelligence</p><h2 className="mt-1 text-lg font-semibold">Model quality at threshold</h2><div className="mt-6 flex items-end justify-between"><span className="font-mono text-4xl text-primary">{threshold.toFixed(2)}</span><span className="font-mono text-[10px] text-muted-foreground">{metrics.positives} POSITIVE CALLS</span></div><Slider className="mt-4" value={[threshold]} min={0.05} max={0.95} step={0.01} onValueChange={(value) => setThreshold(value[0] ?? threshold)} aria-label="Decision threshold" /><div className="mt-6 grid grid-cols-3 gap-2"><Quality label="Precision" value={metrics.precision} /><Quality label="Recall" value={metrics.recall} /><Quality label="F1" value={metrics.f1} /></div><p className="mt-5 border-t border-border/60 pt-4 text-xs leading-5 text-muted-foreground">Metrics recalculate against current reviewed outcomes as the decision threshold moves.</p></div>
    </section>
  </div>;
}

function Metric({ icon, label, value, detail, danger = false }: { icon: ReactNode; label: string; value: string; detail: string; danger?: boolean }) { return <div className={cn("glass-panel relative min-h-44 overflow-hidden rounded-md p-5", danger && "border-destructive/25")}><div className={cn("grid size-9 place-items-center border bg-primary/10 text-primary", danger && "border-destructive/25 bg-destructive/10 text-destructive")}>{icon}</div><p className="mt-5 font-mono text-[10px] uppercase text-muted-foreground">{label}</p><p className="mt-1 text-3xl font-semibold">{value}</p><p className="mt-2 font-mono text-[10px] text-muted-foreground">{detail}</p></div>; }
function Quality({ label, value }: { label: string; value: number }) { return <div className="border border-border/60 bg-background/35 p-3 text-center"><p className="font-mono text-[9px] uppercase text-muted-foreground">{label}</p><p className="mt-2 font-mono text-lg text-emerald-400">{(value * 100).toFixed(1)}%</p></div>; }

function TransactionStream({ transactions }: { transactions: Transaction[] }) {
  const [query, setQuery] = useState(""); const [filter, setFilter] = useState("all");
  const filtered = useMemo(() => transactions.filter((row) => {
    const search = query.trim().toLowerCase();
    const matchesSearch = !search || row.card_holder.toLowerCase().includes(search) || row.location.toLowerCase().includes(search) || row.status.toLowerCase().includes(search);
    return matchesSearch && (filter === "all" || row.status.toLowerCase() === filter);
  }), [transactions, query, filter]);
  return <section className="glass-panel overflow-hidden rounded-md"><div className="border-b border-border/70 p-5"><div className="flex flex-col gap-3 lg:flex-row lg:items-end lg:justify-between"><div><p className="font-mono text-[10px] uppercase text-primary">Realtime anomaly map</p><h2 className="mt-1 text-xl font-semibold">Monitored transaction stream</h2></div><div className="flex flex-col gap-2 sm:flex-row"><div className="relative"><Search className="absolute left-3 top-1/2 size-4 -translate-y-1/2 text-muted-foreground" /><Input value={query} onChange={(event) => setQuery(event.target.value.slice(0, 100))} placeholder="Search holder, city, status" className="w-full bg-background/50 pl-9 sm:w-72" aria-label="Search transactions" /></div><Select value={filter} onValueChange={setFilter}><SelectTrigger className="bg-background/50 sm:w-44" aria-label="Filter risk classification"><SelectValue /></SelectTrigger><SelectContent><SelectItem value="all">All classifications</SelectItem><SelectItem value="cleared">Cleared</SelectItem><SelectItem value="flagged">Flagged</SelectItem><SelectItem value="blocked">Blocked</SelectItem></SelectContent></Select></div></div><div className="mt-3 flex items-center justify-between font-mono text-[10px]"><span className="text-muted-foreground">{filtered.length} OF {transactions.length} RECORDS</span><span className="flex items-center gap-2 text-emerald-400"><span className="size-2 animate-pulse rounded-full bg-emerald-400" /> ENCRYPTED CHANNEL ACTIVE</span></div></div><div className="overflow-x-auto"><Table><TableHeader><TableRow><TableHead className="pl-5">Timestamp</TableHead><TableHead>Card holder</TableHead><TableHead>Transaction city</TableHead><TableHead>Amount</TableHead><TableHead>ML anomaly risk</TableHead><TableHead className="pr-5 text-right">Status</TableHead></TableRow></TableHeader><TableBody>{filtered.map((row) => <TransactionRow key={row.id} transaction={row} />)}{filtered.length === 0 && <TableRow><TableCell colSpan={6} className="h-40 text-center text-muted-foreground">No transactions match this view.</TableCell></TableRow>}</TableBody></Table></div></section>;
}
function TransactionRow({ transaction }: { transaction: Transaction }) { const score = Number(transaction.risk_score); return <TableRow className="border-border/40 hover:bg-accent/30"><TableCell className="pl-5 font-mono text-xs text-muted-foreground">{timeLabel(transaction.timestamp)}</TableCell><TableCell className="min-w-40 font-medium">{transaction.card_holder}</TableCell><TableCell className="min-w-40 text-muted-foreground"><span className="flex items-center gap-2"><Globe2 className="size-3 text-primary" />{transaction.location}</span></TableCell><TableCell className="font-mono">{money(transaction.amount)}</TableCell><TableCell><div className="flex min-w-32 items-center gap-3"><div className="h-1 flex-1 overflow-hidden bg-muted"><div className={cn("h-full", score >= 80 ? "bg-destructive" : score >= 50 ? "bg-amber-400" : "bg-emerald-400")} style={{ width: `${score}%` }} /></div><span className={cn("w-10 font-mono text-xs", riskTone(score))}>{score}%</span></div></TableCell><TableCell className="pr-5 text-right"><Badge variant="outline" className={cn("font-mono text-[9px] uppercase", statusStyle(transaction.status), transaction.status === "Blocked" && "animate-alert-pulse")}>{transaction.status}</Badge></TableCell></TableRow>; }

function RiskSandbox({ threshold }: { threshold: number }) {
  const analyze = useServerFn(analyzeTransaction); const scoreBatch = useServerFn(scoreTransactionBatch); const queryClient = useQueryClient();
  const [values, setValues] = useState(initialVector); const [result, setResult] = useState<ReturnType<typeof scoreFraudVector> | null>(null); const [open, setOpen] = useState(false); const [working, setWorking] = useState(false); const [batch, setBatch] = useState<BatchResult[]>([]); const [fileError, setFileError] = useState(""); const [dragging, setDragging] = useState(false); const inputRef = useRef<HTMLInputElement>(null);
  const preview = scoreFraudVector(values, threshold);
  const update = (key: keyof SandboxValues, value: number) => setValues((current) => ({ ...current, [key]: value }));
  const run = async () => { setWorking(true); try { const response = await analyze({ data: { ...values, threshold } }); setResult(response); setOpen(response.status !== "Cleared"); await queryClient.invalidateQueries({ queryKey: transactionsQuery.queryKey }); } finally { setWorking(false); } };
  const processFile = async (file?: File) => { if (!file) return; setFileError(""); setWorking(true); try { const parsed = parseCsv(await file.text(), threshold); const response = await scoreBatch({ data: { rows: parsed } }); setBatch(response); await queryClient.invalidateQueries({ queryKey: transactionsQuery.queryKey }); } catch (error) { setFileError(error instanceof Error ? error.message : "Unable to score this file."); } finally { setWorking(false); setDragging(false); } };
  const exportCsv = () => { if (!batch.length) return; const header = "card_holder,location,amount,time,V14,V4,V12,V10,risk_score,status"; const rows = batch.map((row) => [row.cardHolder, row.location, row.amount, row.time, row.v14, row.v4, row.v12, row.v10, row.riskScore, row.status].map(csvCell).join(",")); const url = URL.createObjectURL(new Blob([[header, ...rows].join("\n")], { type: "text/csv;charset=utf-8" })); const link = document.createElement("a"); link.href = url; link.download = "finshield-scored-transactions.csv"; link.click(); URL.revokeObjectURL(url); };
  return <><section className="grid gap-5 xl:grid-cols-[minmax(0,1.25fr)_minmax(320px,.75fr)]"><div className="glass-panel rounded-md p-5 sm:p-7"><div className="flex items-start justify-between"><div><p className="font-mono text-[10px] uppercase text-primary">Individual testing</p><h2 className="mt-1 text-2xl font-semibold">PCA Vector Diagnostics</h2><p className="mt-2 max-w-xl text-sm leading-6 text-muted-foreground">Evaluate six features through the integrated boosted-tree risk engine.</p></div><Sparkles className="text-primary" /></div><div className="mt-8 grid gap-x-8 gap-y-7 sm:grid-cols-2">{vectorFields.map(([key, label, min, max, step, unit]) => <VectorControl key={key} name={label} unit={unit} value={values[key]} min={min} max={max} step={step} onChange={(value) => update(key, value)} />)}</div><Button variant="command" size="lg" className="mt-9 w-full sm:w-auto" onClick={run} disabled={working}>{working ? <Activity className="animate-spin" /> : <ScanLine />}{working ? "Running diagnostics…" : "Run Vector Diagnostics"}</Button></div><aside className="glass-panel rounded-md p-5 sm:p-7"><p className="font-mono text-[10px] uppercase text-primary">Live model output</p><div className="mt-2 flex items-end justify-between"><h3 className="text-lg font-semibold">Decision preview</h3><span className={cn("font-mono text-4xl", riskTone(preview.riskScore))}>{preview.riskScore}%</span></div><Badge variant="outline" className={cn("mt-4", statusStyle(preview.status))}>{preview.status}</Badge><div className="mt-6 space-y-3"><PolicyRule active={values.amount > 5000} label="Amount > $5,000" value={money(values.amount)} /><PolicyRule active={values.v14 < -2.5} label="V14 < -2.5" value={values.v14.toFixed(2)} /><PolicyRule active={values.v4 > 2} label="V4 > 2.0" value={values.v4.toFixed(2)} /><PolicyRule active={values.v12 < -2} label="V12 < -2.0" value={values.v12.toFixed(2)} /></div><div className="mt-6 border-t border-border/60 pt-5"><p className="font-mono text-[10px] uppercase text-muted-foreground">Dominant model signals</p>{preview.signals.length ? preview.signals.map((signal) => <div key={signal.label} className="mt-3 flex items-center justify-between text-xs"><span>{signal.label}</span><span className="font-mono text-primary">+{signal.impact.toFixed(2)}</span></div>) : <p className="mt-3 text-xs text-emerald-400">No material anomaly signal.</p>}</div></aside></section><CsvHub batch={batch} error={fileError} working={working} dragging={dragging} setDragging={setDragging} inputRef={inputRef} onFile={processFile} onExport={exportCsv} /><ResultDialog result={result} open={open} onOpenChange={setOpen} /></>;
}

function VectorControl({ name, unit, value, min, max, step, onChange }: { name: string; unit: string; value: number; min: number; max: number; step: number; onChange: (value: number) => void }) { return <div><div className="mb-3 flex items-center justify-between"><label htmlFor={`vector-${name}`} className="font-mono text-xs">{name}</label><div className="flex w-28 items-center"><span className="mr-1 font-mono text-xs text-primary">{unit}</span><Input id={`vector-${name}`} type="number" value={value} min={min} max={max} step={step} onChange={(event) => { const next = Number(event.target.value); if (Number.isFinite(next)) onChange(Math.min(max, Math.max(min, next))); }} className="h-8 bg-background/50 text-right font-mono text-xs" /></div></div><Slider value={[value]} min={min} max={max} step={step} onValueChange={(next) => onChange(next[0] ?? value)} aria-label={name} /></div>; }
function PolicyRule({ active, label, value }: { active: boolean; label: string; value: string }) { return <div className={cn("flex items-center justify-between border p-3 transition-colors", active ? "border-destructive/50 bg-destructive/10" : "border-border/60 bg-background/30")}><div className="flex items-center gap-3">{active ? <ShieldX className="size-4 text-destructive" /> : <ShieldCheck className="size-4 text-emerald-400" />}<span className="text-xs">{label}</span></div><span className={cn("font-mono text-xs", active ? "text-destructive" : "text-muted-foreground")}>{value}</span></div>; }

function CsvHub({ batch, error, working, dragging, setDragging, inputRef, onFile, onExport }: { batch: BatchResult[]; error: string; working: boolean; dragging: boolean; setDragging: (value: boolean) => void; inputRef: React.RefObject<HTMLInputElement | null>; onFile: (file?: File) => void; onExport: () => void }) {
  const drop = (event: DragEvent<HTMLDivElement>) => { event.preventDefault(); void onFile(event.dataTransfer.files[0]); };
  return <section className="glass-panel mt-5 rounded-md p-5 sm:p-7"><div className="flex flex-col gap-3 sm:flex-row sm:items-end sm:justify-between"><div><p className="font-mono text-[10px] uppercase text-primary">CSV operations hub</p><h2 className="mt-1 text-xl font-semibold">Batch anomaly scoring</h2><p className="mt-2 text-sm text-muted-foreground">Required columns: amount, time, V14, V4, V12, V10. Holder and location are optional.</p></div><Button variant="terminal" onClick={onExport} disabled={!batch.length}><Download /> Export Scored Sheet</Button></div><input ref={inputRef} type="file" accept=".csv,text/csv" className="hidden" onChange={(event) => void onFile(event.target.files?.[0])} /><div role="button" tabIndex={0} onClick={() => inputRef.current?.click()} onKeyDown={(event) => { if (event.key === "Enter" || event.key === " ") inputRef.current?.click(); }} onDragOver={(event) => { event.preventDefault(); setDragging(true); }} onDragLeave={() => setDragging(false)} onDrop={drop} className={cn("mt-6 grid min-h-40 cursor-pointer place-items-center border border-dashed p-6 text-center transition-colors", dragging ? "border-primary bg-primary/10" : "border-border bg-background/25 hover:border-primary/50")}><div><UploadCloud className="mx-auto size-8 text-primary" /><p className="mt-3 text-sm font-medium">Drop a transaction CSV or select a file</p><p className="mt-1 font-mono text-[10px] text-muted-foreground">UP TO 500 RECORDS · PROCESSED LOCALLY</p></div></div>{error && <p role="alert" className="mt-3 text-sm text-destructive">{error}</p>}{working && <div className="mt-4 flex items-center gap-2 font-mono text-xs text-primary"><Activity className="size-4 animate-spin" /> Scoring and securing records…</div>}{batch.length > 0 && <div className="mt-6 overflow-x-auto"><Table><TableHeader><TableRow><TableHead>Rank</TableHead><TableHead>Card holder</TableHead><TableHead>Location</TableHead><TableHead>Amount</TableHead><TableHead>Risk</TableHead><TableHead>Status</TableHead></TableRow></TableHeader><TableBody>{batch.map((row, index) => <TableRow key={`${row.cardHolder}-${index}`}><TableCell className="font-mono text-muted-foreground">{String(index + 1).padStart(2, "0")}</TableCell><TableCell>{row.cardHolder}</TableCell><TableCell>{row.location}</TableCell><TableCell className="font-mono">{money(row.amount)}</TableCell><TableCell className={cn("font-mono", riskTone(row.riskScore))}>{row.riskScore}%</TableCell><TableCell><Badge variant="outline" className={statusStyle(row.status)}>{row.status}</Badge></TableCell></TableRow>)}</TableBody></Table></div>}</section>;
}

function ResultDialog({ result, open, onOpenChange }: { result: ReturnType<typeof scoreFraudVector> | null; open: boolean; onOpenChange: (open: boolean) => void }) { const blocked = result?.status === "Blocked"; return <Dialog open={open} onOpenChange={onOpenChange}><DialogContent className="overflow-hidden border-destructive/55 bg-popover crimson-glow sm:max-w-md"><div className="absolute inset-x-0 top-0 h-1 animate-alert-pulse bg-destructive" /><DialogHeader className="items-center text-center"><div className="mb-3 grid size-16 place-items-center rounded-full border border-destructive/50 bg-destructive/10 text-destructive">{blocked ? <ShieldX className="size-8" /> : <AlertTriangle className="size-8" />}</div><DialogTitle className="text-2xl text-destructive">{blocked ? "Transaction Blocked" : "Anomaly Flagged"}</DialogTitle><DialogDescription>{blocked ? "A critical hard-rule signature intercepted this payment." : "This vector crossed the current review threshold and requires investigation."}</DialogDescription></DialogHeader><div className="my-2 border-y border-border/70 py-5 text-center"><p className="font-mono text-[10px] uppercase text-muted-foreground">Integrated model risk</p><p className="mt-2 font-mono text-5xl text-destructive">{result?.riskScore ?? 0}<span className="text-xl">%</span></p></div><DialogFooter><Button variant="destructive" className="w-full" onClick={() => onOpenChange(false)}><AlertTriangle /> Acknowledge alert</Button></DialogFooter></DialogContent></Dialog>; }

function parseCsv(text: string, threshold: number) {
  const lines = text.replace(/^\uFEFF/, "").split(/\r?\n/).filter((line) => line.trim());
  if (lines.length < 2) throw new Error("The CSV needs a header and at least one transaction.");
  const parseLine = (line: string) => { const cells: string[] = []; let value = ""; let quoted = false; for (let index = 0; index < line.length; index += 1) { const char = line[index]; if (char === '"' && quoted && line[index + 1] === '"') { value += '"'; index += 1; } else if (char === '"') quoted = !quoted; else if (char === "," && !quoted) { cells.push(value.trim()); value = ""; } else value += char; } cells.push(value.trim()); return cells; };
  const headers = parseLine(lines[0] ?? "").map((header) => header.toLowerCase().replace(/[^a-z0-9]/g, ""));
  const indexOf = (...names: string[]) => headers.findIndex((header) => names.includes(header));
  const indexes = { amount: indexOf("amount"), time: indexOf("time"), v14: indexOf("v14"), v4: indexOf("v4"), v12: indexOf("v12"), v10: indexOf("v10"), holder: indexOf("cardholder", "cardholdername", "name"), location: indexOf("location", "city") };
  if ([indexes.amount, indexes.time, indexes.v14, indexes.v4, indexes.v12, indexes.v10].some((index) => index < 0)) throw new Error("Missing required columns: Amount, Time, V14, V4, V12, V10.");
  if (lines.length - 1 > 500) throw new Error("A batch can contain at most 500 transactions.");
  return lines.slice(1).map((line, rowIndex) => { const cells = parseLine(line); const read = (index: number, name: string) => { const value = Number(cells[index]); if (!Number.isFinite(value)) throw new Error(`Row ${rowIndex + 2}: ${name} must be numeric.`); return value; }; return { amount: read(indexes.amount, "Amount"), time: read(indexes.time, "Time"), v14: read(indexes.v14, "V14"), v4: read(indexes.v4, "V4"), v12: read(indexes.v12, "V12"), v10: read(indexes.v10, "V10"), cardHolder: indexes.holder >= 0 && cells[indexes.holder] ? String(cells[indexes.holder]).slice(0, 100) : `Batch Card •••• ${String(rowIndex + 1).padStart(4, "0")}`, location: indexes.location >= 0 && cells[indexes.location] ? String(cells[indexes.location]).slice(0, 100) : "CSV Intake", threshold }; });
}
function csvCell(value: string | number) { const text = String(value); return /[",\n]/.test(text) ? `"${text.replace(/"/g, '""')}"` : text; }
